### ISSUE TITLE
What is the purpose of the `value` column?

### ISSUE THREAD

**Issue by joshlemer** [dekses/cassandra-lock#10]
I see from the create table statement, that the lock_leases table has a `value text` column:

```cql
CREATE TABLE lock_leases (
    name text PRIMARY KEY,
    owner text,
    value text
) WITH default_time_to_live = 60;
```
But the column is never used anywhere in the repository. Does it serve some other purpose that isn't obvious?

**Comment by ysubach** [comment]
I think it was copied from https://www.datastax.com/blog/consensus-cassandra assuming leases can have optional values. But it was never implemented in code.
