### ISSUE TITLE
Maven central

### ISSUE THREAD

**Issue by lucius-pl** [dekses/cassandra-lock#6]
Would be possible to upload this project to Maven central. I use AWS CodeBuild and it would be very helpful for me. Thanks in advance.

**Comment by ysubach** [comment]
Sounds like a really good idea. I'll work on it once latest PRs merged.

**Comment by chrisribble** [comment]
:+1:

**Comment by lucius-pl** [comment]
@ysubach Do you know when your project would be available in Maven Central? Thanks.

**Comment by ysubach** [comment]
Yes, I'll publish it this week.

**Comment by ysubach** [comment]
Took some time to set up things for release. Version 0.0.2 is ready to go.
Unfortunately it does not include latest fix from @chrisribble which I'll publish with version 0.0.3 in  couple of days.

**Comment by ysubach** [comment]
Released version 0.0.3 and published to Maven Central.
