### ISSUE TITLE
Thoughts on using LOCAL_SERIAL instead of SERIAL

### ISSUE THREAD

**Issue by cc-cpo** [dekses/cassandra-lock#8]
Hello,
thanks for your work. We are using your solution in production for some years now.

As we are operating in two DCs, I wonder if it breaks the guarantees of your library when I start using LOCAL_SERIAL instead of SERIAL and LOCAL_QUORUM instead of QUORUM?
Our point of using LOCAL_x is that we want to survive the outage of one of our two DCs.

Do you have any thoughts / recommendations on that?

Thank you very much!

Stefan

**Comment by ysubach** [comment]
Hi Stefan,

Happy to hear it works well for you.

The question you are asking is very interesting. Let me think about it and come back in a few days.

**Comment by ysubach** [comment]
Hi Stefan,

Usage of LOCAL_x consistency level is going to change library operation significantly. It'll guarantee consistency (and locks integrity) only within DC performing the operation. In the situation with 2 DCs it means that you'll definitely survive other DC outage. But it creates a situation when processes in both DCs will be able acquire the same lock.

I think LOCAL_x consistency is going to work *only* if you can guarantee that only one DC at a time is performing operations with locks.

I don't have enough details about the way you use DCs or the nature of operations that's protected by locks, so not sure what's the best way to proceed. If you are not comfortable disclosing more details via Github shoot me an email at yuri@dekses.com

Hope it helps.

- Yuri

**Comment by cc-cpo** [comment]
Hello Yuri, that was my feeling too. We definitely want to have cluster-wide locks, so we will stick with the SERIAL/QUORUM mode.
Thanks for clarifying.

Regards,

Stefan
